FROM python:3.12.0b3-alpine3.18
ENV AWS_CONFIG_PATH=/config/
ENV HEALTHCHECK_HEARTBEAT_FILE=/usr/src/app/heartbeat
ENV HEALTHCHECK_INTERVAL_FILE=/usr/src/app/max_age
ENV AWS_SHARED_CREDENTIALS_FILE=/config/credentials
ENV AWS_DOCKER_VERSION="2.2.1.0"
WORKDIR /usr/src/app
#RUN apk add nano
RUN apk add tzdata
#COPY requirements.txt ./
COPY ./app .
RUN pip install --no-cache-dir -r requirements.txt
RUN mv healthcheck_python_alpine.sh healthcheck.sh
RUN rm healthcheck_ubuntu.sh
RUN chmod +x healthcheck.sh
RUN rm put_python_app_here
RUN rm requirements.txt
HEALTHCHECK --start-period=60s --interval=120s --retries=2 CMD sh -c '/usr/src/app/healthcheck.sh' 
CMD [ "python", "./AWS_Route53_DDNS.py" ]
